package test.tasks.userservice.exceptions;

public class UserAlreadyExistsException extends Exception {
}
